import fs from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

const SPEC_PATH = new URL("../api-docs.yaml", import.meta.url); // 先用“修正后的”
const OUT_PATH = new URL("../src/api/schema.d.ts", import.meta.url);

// 你可以选 File 或 Blob；浏览器上传更常用 File
const FILE = ts.factory.createTypeReferenceNode("File");

const ast = await openapiTS(SPEC_PATH, {
    transform(schemaObject) {
        if (schemaObject?.format === "binary") {
            return FILE; // 让 file 字段在 TS 里变成 File
        }
    },
    // 让 d.ts 顶部确保有 File 类型（浏览器环境通常已有，这行可选）
    inject: `// generated by openapi-typescript\n`,
});

fs.mkdirSync(new URL("../src/api/", import.meta.url), { recursive: true });
fs.writeFileSync(OUT_PATH, astToString(ast));
console.log("✅ generated:", OUT_PATH.pathname);
